### ISSUE TITLE
Toasts aren't going away after launching multiple times

### ISSUE THREAD

**Issue by jinyus** [kbrgl/svelte-french-toast#19]
When launching the toast a 2nd time, it doesn't hide automatically.

Demo (launch toast once, wait a 2secs then launch again to see issue):
https://french-toast-demo.surge.sh/

repo: https://github.com/jinyus/toastr

video of the issue:

https://user-images.githubusercontent.com/30532952/210676089-f1569de5-3ffd-415b-9bd4-cccac8295bf8.mp4

**Comment by kbrgl** [comment]
Can you use a different ID for the subsequent toasts and try again? Since the toast is already closed, using the same ID shouldn't work.

**Comment by jinyus** [comment]
This worked, thanks.
