### ISSUE TITLE
Is this project still maintained? (TL;DR: Yes.)

### ISSUE THREAD

**Issue by ja3abuser** [kbrgl/svelte-french-toast#21]
Is the project still supported? The last commit was 6 months ago and I don't know if I can use it in my project.

**Comment by kbrgl** [comment]
TL;DR: Sort of.

I'm still personally invested in this project, but I'm also an undergrad with lots of competing priorities. So while I will respond to bug reports and guide you towards a fix, I probably won't be adding more features or merging anything until summer rolls around and I've got free time.

SFT right now works... well enough. If you're trying to evaluate whether to use it, go through the existing issues and see if there are any dealbreakers. Short of those, I think SFT is the most polished toast library for Svelte, but of course I might be biased. 😄
