### ISSUE TITLE
Are there any real examples of using rich text and promise toasts?

### ISSUE THREAD

**Issue by jakubdonovan** [kbrgl/svelte-french-toast#23]
I'm looking through the docs and I can't figure out how to use rich text in my toasts. Are there any real examples?

**Comment by kbrgl** [comment]
If you scroll down to the bottom of the docs, there should be a button called "Rich content" that shows you a demo of rich text as well as how to implement it. You need to create a Svelte component (say RichText.svelte) which contains your rich text (i.e. any HTML markup). Then just import it wherever you're creating your toasts and call toast with `toast(RichText)`.

**Comment by kbrgl** [comment]
Let me know if that works for you or if you have a different use case that's not addressed by the docs!
