### ISSUE TITLE
RTL support?

### ISSUE THREAD

**Issue by amr3k** [kbrgl/svelte-french-toast#28]
the positions are invalid for RTL layouts. the `bottom-left` for example appear on the right side, and vice versa.

Here's a [repl](https://svelte.dev/repl/6b1413d287d94eb4b6966a359e695615)

**Comment by kbrgl** [comment]
Thanks for reporting this issue! I could be down to accept a PR if it's just 5-6 lines of additional code (perhaps using the `:dir()` selector).

**Comment by amr3k** [comment]
[`:dir()` is not widely supported](https://caniuse.com/css-dir-pseudo)
