### ISSUE TITLE
Publish type issue fix to npm

### ISSUE THREAD

**Issue by shiftlabs1** [kbrgl/svelte-french-toast#29]
Hi @kbrgl ,
I see that the PR https://github.com/kbrgl/svelte-french-toast/pull/25 to fix type issues for Promise style toast has been merged into master for some time but was not published to npm. Can you please publish this so we can use that feature especially for production builds that run remotely on github using containers? While one can fix the source file in node_modules locally, we can't do this in those remote builds

**Comment by kbrgl** [comment]
Publishing now! Should be up in a few minutes.
