### ISSUE TITLE
Know result of promise

### ISSUE THREAD

**Issue by jorri11** [kbrgl/svelte-french-toast#31]
Is there a way to know the result of toast.promise()?

**Comment by li6in9muyou** [comment]
Can you clarify your question please?

The promise you passed in is returned back from `toast.promise(...)`, see source below.

https://github.com/kbrgl/svelte-french-toast/blob/8cc73ee80ac5bfeb592e97d28f4c99b25f96aa29/src/lib/core/toast.ts#L52-L81

You can try it out in [this REPL](https://svelte.dev/repl/35864091397649acb6b5ed430a22defb?version=3.56.0)

**Comment by kbrgl** [comment]
Thanks for the demo @li6in9muyou!

To clarify further, once a promise is fulfilled, awaiting it a second time should have no effect: https://blog.scottlogic.com/2021/01/07/await-twice.html.

So if you do `await toast.promise(p, ...)`, it's roughly the same as doing `await p`, except Svelte French Toast adds some side effects.
