### ISSUE TITLE
Domain expired?

### ISSUE THREAD

**Issue by khromov** [kbrgl/svelte-french-toast#36]
I noticed that https://svelte-french-toast.com seems to have expired. It would be really nice to deploy the original site to something like GitHub pages since it contained a lot of good information!

**Comment by okuruu** [comment]
Agree with this. 
I can't access the site while I need to read the docs.

**Comment by kylesloper** [comment]
Found the vercel site: https://svelte-french-toast.vercel.app

**Comment by kbrgl** [comment]
Oof, forgot to turn on auto-renew. I’ll have it back up soon. Thanks for the issue!

**Comment by kbrgl** [comment]
Alright, I think the URL should be working. It might go down again for a bit since I initiated a transfer from Namecheap to Porkbun which is my main registrar. In the meantime you can use the Vercel website linked by @kylesloper.
