### ISSUE TITLE
Toast offset should update when toast updates

### ISSUE THREAD

**Issue by BlueGreenMagick** [kbrgl/svelte-french-toast#51]
When a toast is modified, its height can change, which should update the toast offsets for all other toasts.

For example, in the below code the updated toast is stacked on top of another toast below.
```js
toast.promise(promise, {
loading: 'Saving...',
success: `Settings saved! This message extends across multiple lines.`,
error: `Could not save. This message extends across multiple lines.`
});
```

**Comment by BlueGreenMagick** [comment]
![image](https://github.com/kbrgl/svelte-french-toast/assets/50060875/87158e72-9b53-4125-b7e4-5d731762424e)

**Comment by kbrgl** [comment]
Holy cow that's ugly. Thanks for reporting this issue, will investigate. I’m looking into moving to a flexbox based approach where I don't do manual offset calculations so that this issue doesn't come up.
