### ISSUE TITLE
Can I use this awesome package in Sveltekit?

### ISSUE THREAD

**Issue by hardcommitoneself** [kbrgl/svelte-french-toast#52]
When I add this package to my Sveltekit project, some errors are encountered.

```
Internal server error: Failed to resolve entry for package "svelte-french-toast". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "svelte-french-toast" package
```

**Comment by NickRTR** [comment]
Hey @hardcommitoneself,

I'm using this package in a current SvelteKit project just fine. Could you share the code that implements the package with me? This way I might find what your problem is and will probably be able to help you resolving it.

**Comment by sooluh** [comment]
Same here, mate. I'm using it in SvelteKit ^1.5.0 with Svelte version at ^3.54.0. I import and use it just like in the tutorial provided, and there's no issue in the IDE I'm using. However, it's problematic in both the terminal and the browser. The error message is exactly the same:

> Error: Failed to resolve entry for package "svelte-french-toast". The package might have incorrect main/module/exports specified in its package.json: No known conditions for the "." specifier in the "svelte-french-toast" package.

**Comment by kbrgl** [comment]
+1 to all the comments. I use Svelte French Toast with SvelteKit all the time.
