### ISSUE TITLE
Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by fell-lucas** [kbrgl/svelte-french-toast#55]
Hi! When running the server, this bunch of error logs show up:

<img width="1009" alt="image" src="https://github.com/kbrgl/svelte-french-toast/assets/47724710/8a2b2a7f-960d-4c9f-ad57-1eddcb75b699">

However, when I wrap `<Toaster />` with an `if browser` from SvelteKit, the error stops happening:
<img width="141" alt="image" src="https://github.com/kbrgl/svelte-french-toast/assets/47724710/6cf808d0-fad5-4d3a-af9d-5a6d004bb14d">
`browser` is imported from `'$app/environment'`

Just opening the issue here in case there are some other people out there that are also experiencing this.

Thanks for this amazing library! We've been using for a few months now and it's been great.

**Comment by kbrgl** [comment]
Hey Lucas! Thanks for the report. If possible, could you provide a minimal reproduction? Going to leave this issue open in case others run into it.

**Comment by fell-lucas** [comment]
Hi, sorry for the delay. I've removed the `if browser` statement and will be keeping an eye on the logs to check if it happens again. If I recall correctly, even when throwing this error, the toast was still being shown, so it wasn't a major issue or anything.

If something happens I'll update here, but feel free to close the issue.
