### ISSUE TITLE
Can I place it to the vertical center of the page?

### ISSUE THREAD

**Issue by zed-wong** [kbrgl/svelte-french-toast#63]
I've seen there're only top and bottom positions. Can we place it to the center of the page? Top and bottom doesn't work really well in my case.

**Comment by kbrgl** [comment]
Yep—you can do any position! See https://github.com/kbrgl/svelte-french-toast/blob/9a3aef01b495bf01380edfea11ca3f108ff526ed/src/lib/core/types.ts#L11.

**Comment by zed-wong** [comment]
> Yep—you can do any position! See the following:
> 
> https://github.com/kbrgl/svelte-french-toast/blob/9a3aef01b495bf01380edfea11ca3f108ff526ed/src/lib/core/types.ts#L11

But looks like I can't do vertically center and horizontally center at the same time
